store:
  memory:
    limit: 1000

auth:
  auth-memory:
    users:
      test:
        name: test
        password: test

listen:
  - http://localhost:4873

web:
  enable: true

uplinks:
  npmjs:
    url: https://registry.npmjs.org

logs:
  - { type: stdout, format: pretty, level: warn }

packages:
  'aws-prototyping-sdk':
    access: $all
    publish: $all
  '@*/*':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs
  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

_debug: true